COMMON:
  NAME: "Awesome-Digital-Human"
  VERSION: "v3.0.0"
  LOG_LEVEL: "DEBUG"
SERVER:
  IP: "0.0.0.0"
  PORT: 6006
  STORAGE_DOMAIN: "https://light4ai.space"
  WORKSPACE_PATH: "./outputs"
  ENGINES:
    ASR: 
      SUPPORT_LIST: [ "difyAPI.yaml", "tencentAPI.yaml" ]
      DEFAULT: "difyAPI.yaml"
    TTS: 
      SUPPORT_LIST: [ "edgeAPI.yaml", "tencentAPI.yaml", "difyAPI.yaml" ]
      DEFAULT: "edgeAPI.yaml"
    LLM: 
      SUPPORT_LIST: []
      DEFAULT: ""
  AGENTS: 
    SUPPORT_LIST: [ "repeaterAgent.yaml", "openaiAPI.yaml", "difyAgent.yaml", "fastgptAgent.yaml" ]
    DEFAULT: "repeaterAgent.yaml"
